### ISSUE TITLE
I am getting error at the time of making build

### ISSUE THREAD

**Issue by umar28dec** [didinj/mean-angular4-chat-app#5]
`ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/var/www/html/node/mean-angular4-chat-app/src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts
[root@localhost mean-angular4-chat-app]# `

**Comment by apvpn** [comment]
I am getting same error !

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'E:\Public_html\mean-projects\mean-angular4-chat-app\src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts

**Comment by apvpn** [comment]
anyone has idea for resolution ?

**Comment by apvpn** [comment]
I could resolve above issue and made build successfully using below command:
`ng build --env=prod`

**Comment by louistone** [comment]
$ ng build --env=prod

It works. Thanks! @apvpn

**Comment by umar28dec** [comment]
It works for me as well.
Thanks
